services:
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: php-fpm
    volumes:
      - ./src:/var/www/html
      - ./.env:/var/www/.env
    networks:
      - backend

  nginx:
    image: nginx:alpine
    container_name: nginx-server
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
      - ./public:/var/www/public
    ports:
      - '8080:80'
    networks:
      - backend
    depends_on:
      - php
    restart: always

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend
    ports:
      - "3306:3306"
    restart: always

networks:
  backend:
    driver: bridge

volumes:
  mysql_data:
